name: Prod Pipeline

on:
  push:
    branches: [ "main" ]   # jab main branch pe push hoga tab chalega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # latest version

      - name: Prepare clean package
        run: |
          mkdir app_package
          rsync -av --progress ./ app_package \
            --exclude .git \
            --exclude .gitignore \
            --exclude .github \
            --exclude .azure-pipelines \
            --exclude '*.yml' \
            --exclude '*.env' \
            --exclude 'node_modules' \
            --exclude 'venv' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            --exclude '*.log' \
            --exclude '*.sqlite3'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: app_package

      # Docker build step
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Agar DockerHub pe push karna ho to ye steps enable karo:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mydockerhubusername/myapp:latest

